/**
 * Database access for office-server (SPEC §4.2, §5; research 01 §9).
 *
 * A single Bun process owns the SQLite file. `openDatabase` applies the
 * connection pragmas (WAL, busy timeout, foreign keys); `runMigrations`
 * applies the SQL migrations under `apps/server/drizzle/` generated by
 * drizzle-kit from `./schema`. Boot wiring (`openDatabase` then
 * `runMigrations`) is done by the server entry point.
 *
 * App code must stay portable to Postgres: only this module may rely on
 * SQLite-specific statements (the pragmas below).
 */

import { Database } from "bun:sqlite";
import { mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { type BunSQLiteDatabase, drizzle } from "drizzle-orm/bun-sqlite";
import { migrate } from "drizzle-orm/bun-sqlite/migrator";
import * as schema from "./schema/index.ts";

export * as schema from "./schema/index.ts";
export * from "./schema/index.ts";

export const DEFAULT_DB_FILENAME = "office.db";
export const DEFAULT_BUSY_TIMEOUT_MS = 5000;
export const MEMORY_DB_PATH = ":memory:";

/** Directory holding the drizzle-kit migrations shipped with the server. */
export const MIGRATIONS_DIR = resolve(import.meta.dir, "../../drizzle");

export interface DatabaseConfig {
  /** SQLite file path, or `":memory:"` for an in-memory database (tests). */
  path: string;
  /** How long a writer waits on a locked database before failing. */
  busyTimeoutMs?: number;
}

export type Db = BunSQLiteDatabase<typeof schema> & { $client: Database };

/** `<dataDir>/office.db`, the conventional location honoured by scripts/backup.sh. */
export function databasePathFor(dataDir: string): string {
  return join(dataDir, DEFAULT_DB_FILENAME);
}

/**
 * Open (creating if needed) the office database with the pragmas from
 * research 01 §9 applied. Returns a Drizzle handle bound to the schema.
 */
export function openDatabase(config: DatabaseConfig): Db {
  const isMemory = config.path === MEMORY_DB_PATH;
  if (!isMemory) mkdirSync(dirname(resolve(config.path)), { recursive: true });

  const client = new Database(config.path, { create: true, strict: true });
  const busyTimeoutMs = config.busyTimeoutMs ?? DEFAULT_BUSY_TIMEOUT_MS;
  client.run(`PRAGMA busy_timeout = ${Math.max(0, Math.trunc(busyTimeoutMs))}`);
  client.run("PRAGMA foreign_keys = ON");
  if (!isMemory) {
    client.run("PRAGMA journal_mode = WAL");
    client.run("PRAGMA synchronous = NORMAL");
  }

  return drizzle({ client, schema });
}

/** Apply every pending migration from `MIGRATIONS_DIR` (idempotent). */
export function runMigrations(db: Db, migrationsFolder: string = MIGRATIONS_DIR): void {
  migrate(db, { migrationsFolder });
}

/** Checkpoint the WAL and close the underlying connection. */
export function closeDatabase(db: Db): void {
  try {
    db.$client.run("PRAGMA wal_checkpoint(TRUNCATE)");
  } catch {
    // in-memory or already closed; nothing to checkpoint
  }
  db.$client.close();
}
