/** Sample state objects used by tests. Not exported from the package index. */
import type { BuildingState, HumanPresence } from "./building-state.ts";
import type { CompoundState } from "./compound.ts";
import type { HenchmanState, OperationState } from "./operation-state.ts";

export const humanFixture: HumanPresence = {
  sessionId: "s1",
  userId: "u1",
  displayName: "Ante",
  role: "owner",
  avatar: {
    archetype: "scientist",
    outfit: "ivory",
    trim: "teal",
    skin: "tan",
    hair: "white",
    accessory: "goggles",
  },
  operationId: "lobby",
  levelId: "lobby",
  position: { x: 1.5, z: -2.25, heading: 0.5 },
  animation: "walk",
  doing: "heading to the elevator",
  seatId: "",
  sharingScreen: false,
  joinedAt: 1_700_000_000_000,
};

const compoundFixture: CompoundState = {
  width: 64,
  depth: 64,
  tileMetres: 2,
  outsideDepth: 6,
  version: 123_456,
  specialRooms: [
    {
      kind: "lobby",
      gridX: 26,
      gridY: 56,
      width: 12,
      depth: 8,
      doorSide: "north",
      doorX: 31,
      doorY: 56,
    },
  ],
  corridors: [
    { x: 2, y: 54, w: 60, d: 2 },
    { x: 8, y: 52, w: 2, d: 2 },
  ],
  blastDoorX: 30,
  blastDoorY: 64,
  blastDoorWidth: 4,
};

export const buildingFixture: BuildingState = {
  humans: { s1: humanFixture },
  operations: {
    lobby: {
      operationId: "lobby",
      levelId: "lobby",
      name: "Lobby",
      slug: "lobby",
      index: 0,
      paletteId: "teal-cream",
      henchmenWorking: 0,
      henchmenWaiting: 0,
      henchmenTotal: 0,
      humansPresent: 1,
      gridX: 26,
      gridY: 56,
      width: 12,
      depth: 8,
      doorSide: "north",
      doorX: 31,
      doorY: 56,
      buildState: "ready",
      buildEndsAt: 0,
      deskCount: 0,
      decorStyle: "ops_room",
    },
    f1: {
      operationId: "f1",
      levelId: "lv1",
      name: "Regulus Office",
      slug: "regulus-office",
      index: 1,
      paletteId: "oak-sky",
      henchmenWorking: 2,
      henchmenWaiting: 1,
      henchmenTotal: 3,
      humansPresent: 0,
      gridX: 4,
      gridY: 44,
      width: 10,
      depth: 10,
      doorSide: "south",
      doorX: 8,
      doorY: 54,
      buildState: "building",
      buildEndsAt: 1_700_000_020_000,
      deskCount: 3,
      decorStyle: "lab",
    },
  },
  chat: [
    {
      id: "m1",
      userId: "u1",
      displayName: "Ante",
      operationId: "lobby",
      text: "hello office",
      ts: 1_700_000_001_000,
    },
  ],
  jukebox: {
    current: {
      entryId: "e1",
      trackId: "t1",
      title: "Spy Glass",
      artist: "Kevin MacLeod",
      source: "file",
      videoId: "",
      durationMs: 226_977,
      addedBy: "",
      addedByName: "",
    },
    startedAtServerMs: 1_700_000_000_500,
    pausedAtMs: 0,
    playing: true,
    volume: 0.75,
    queue: [
      {
        entryId: "e2",
        trackId: "t2",
        title: "Lo-fi Loop",
        artist: "CC0 Artist",
        source: "youtube",
        videoId: "dQw4w9WgXcQ",
        durationMs: 180_000,
        addedBy: "u1",
        addedByName: "Ante",
      },
    ],
  },
  usage: {
    todayInputTokens: 120_000,
    todayOutputTokens: 30_000,
    todayCacheTokens: 400_000,
    todayCostUsdEstimate: 1.25,
    officeKeysCostUsdEstimate: 0.25,
    activeHumans: 2,
    topHenchmen: [
      {
        agentId: "a1",
        name: "Ada's Claude Code henchman",
        ownerName: "Ada",
        provider: "claude-code",
        tokens: 90_000,
      },
    ],
    dayStart: 1_699_920_000_000,
    observedAt: 1_700_000_002_000,
  },
  pm: {
    enabled: true,
    privilege: "coordinator",
    activity: "patrolling",
    operationId: "f1",
    position: { x: 0, z: 0, heading: 3.14 },
    animation: "walk",
    doing: "visiting Ada",
    targetAgentId: "a1",
    lastBriefAt: 1_700_000_000_000,
  },
  compound: compoundFixture,
  levels: {
    lobby: {
      levelId: "lobby",
      kind: "lobby",
      login: "",
      name: "Lobby",
      order: 0,
      compound: compoundFixture,
    },
    lv1: {
      levelId: "lv1",
      kind: "org",
      login: "regulus-advanced-systems",
      name: "Regulus Advanced Systems",
      order: 1,
      compound: { ...compoundFixture, version: 654_321 },
    },
  },
  blastDoor: {
    phase: "open",
    openedAt: 1_700_000_100_000,
    closesAt: 1_700_000_160_000,
    openedBy: "Ante",
    presses: 3,
  },
  lobbyWhiteboardVersion: 2,
};

export const henchmanFixture: HenchmanState = {
  agentId: "a1",
  ownerUserId: "u1",
  ownerName: "Ante",
  repoId: "r1",
  seatId: "seat-1",
  provider: "claude-code",
  model: "claude-sonnet-4-5",
  effort: "high",
  permissionMode: "auto",
  status: "working",
  action: "editing",
  taskTitle: "Fix #8",
  taskSummary: "Implement protocol package",
  issueNumber: 8,
  prNumber: 0,
  worktreeBranch: "protocol/8-wire-types",
  handRaised: false,
  statusReason: "",
  skin: "standard",
  bubbleEmits: { toolCalls: 12, fileEdits: 4, testRuns: 2, toolFailures: 1 },
  lastActivityAt: 1_700_000_003_000,
};

export const operationFixture: OperationState = {
  operationId: "f1",
  name: "Regulus Office",
  slug: "regulus-office",
  paletteId: "oak-sky",
  layoutTemplateId: "office-l2-small",
  repos: [
    {
      repoId: "r1",
      owner: "regulus-advanced-systems",
      name: "regulus-office",
      defaultBranch: "master",
      isPrimary: true,
    },
  ],
  henchmen: { a1: henchmanFixture },
  desks: {
    "seat-1": { seatId: "seat-1", agentId: "a1" },
    "seat-2": { seatId: "seat-2", agentId: "" },
  },
  decor: {
    d1: {
      id: "d1",
      kind: "picture",
      wallId: "north",
      x: 2,
      y: 1.5,
      w: 1,
      h: 0.75,
      imageUrl: "/uploads/d1.png",
      placedBy: "u1",
    },
  },
  queue: [
    {
      id: "q1",
      position: 0,
      kind: "issue",
      refNumber: 9,
      repoId: "r1",
      title: "#9 Wire the queue",
      prompt: "Implement issue #9",
      provider: "codex",
      model: "gpt-5-codex",
      effort: "",
      permissionMode: "on-request",
      autoWorktree: true,
      state: "queued",
      agentId: "",
      prNumber: 0,
      reason: "",
      createdBy: "u1",
      ownerName: "Ante",
      createdAt: 1_700_000_004_000,
      startedAt: 0,
      finishedAt: 0,
    },
  ],
  issues: {
    "r1#8": {
      repoId: "r1",
      number: 8,
      title: "protocol: enums, room state shapes",
      state: "open",
      labels: ["area:protocol", "type:task"],
      assignees: [],
      author: "azivkovi",
      url: "https://github.com/regulus-advanced-systems/regulus-office/issues/8",
      updatedAt: 1_700_000_005_000,
    },
  },
  pulls: {
    "r1#71": {
      repoId: "r1",
      number: 71,
      title: "Make baseline quality gates green",
      state: "closed",
      labels: [],
      assignees: ["azivkovi"],
      author: "azivkovi",
      url: "https://github.com/regulus-advanced-systems/regulus-office/pull/71",
      updatedAt: 1_700_000_006_000,
      draft: false,
      merged: true,
      headBranch: "ci/71-gates",
      checksState: "success",
      reviewState: "approved",
    },
  },
  services: {
    svc1: {
      id: "svc1",
      agentId: "a1",
      port: 5173,
      url: "/p/f1/a/a1/port/5173/",
      title: "Vite dev server",
      pid: 42,
      address: "0.0.0.0",
      localOnly: false,
      shared: false,
      firstSeenAt: 1_700_000_007_000,
      lastSeenAt: 1_700_000_008_000,
    },
  },
  whiteboardVersion: 3,
  carriedCards: {
    s1: {
      sessionId: "s1",
      userId: "u1",
      cardKind: "issue",
      repoId: "r1",
      number: 8,
      pickedAt: 1_700_000_009_000,
    },
  },
  queueSettings: { maxRunning: 2, maxPerOwner: 1 },
  deskCount: 3,
  decorStyle: "lab",
};
