/** Sample state objects used by tests. Not exported from the package index. */
import type { BuildingState, HumanPresence } from "./building-state.ts";
import type { FloorState, RobotState } from "./floor-state.ts";

export const humanFixture: HumanPresence = {
  sessionId: "s1",
  userId: "u1",
  displayName: "Ante",
  role: "owner",
  avatar: { colorSet: "teal", accessory: "antenna" },
  floorId: "lobby",
  position: { x: 1.5, z: -2.25, heading: 0.5 },
  animation: "walk",
  doing: "heading to the elevator",
  seatId: "",
  sharingScreen: false,
  joinedAt: 1_700_000_000_000,
};

export const buildingFixture: BuildingState = {
  humans: { s1: humanFixture },
  floors: {
    lobby: {
      floorId: "lobby",
      name: "Lobby",
      slug: "lobby",
      index: 0,
      paletteId: "teal-cream",
      robotsWorking: 0,
      robotsWaiting: 0,
      robotsTotal: 0,
      humansPresent: 1,
    },
    f1: {
      floorId: "f1",
      name: "Regulus Office",
      slug: "regulus-office",
      index: 1,
      paletteId: "oak-sky",
      robotsWorking: 2,
      robotsWaiting: 1,
      robotsTotal: 3,
      humansPresent: 0,
    },
  },
  chat: [
    {
      id: "m1",
      userId: "u1",
      displayName: "Ante",
      floorId: "lobby",
      text: "hello office",
      ts: 1_700_000_001_000,
    },
  ],
  jukebox: {
    trackId: "t1",
    startedAtServerMs: 1_700_000_000_500,
    pausedAtMs: 0,
    playing: true,
    volume: 0.75,
    queue: [
      {
        trackId: "t2",
        title: "Lo-fi Loop",
        artist: "CC0 Artist",
        source: "file",
        durationMs: 180_000,
        addedBy: "u1",
      },
    ],
  },
  usage: {
    todayInputTokens: 120_000,
    todayOutputTokens: 30_000,
    todayCacheTokens: 400_000,
    todayCostUsdEstimate: 1.25,
    officeKeysCostUsdEstimate: 0.25,
    activeHumans: 2,
    topRobots: [
      {
        agentId: "a1",
        name: "Ada's Claude Code robot",
        ownerName: "Ada",
        provider: "claude-code",
        tokens: 90_000,
      },
    ],
    dayStart: 1_699_920_000_000,
    observedAt: 1_700_000_002_000,
  },
  pm: {
    enabled: true,
    privilege: "coordinator",
    activity: "patrolling",
    floorId: "f1",
    position: { x: 0, z: 0, heading: 3.14 },
    animation: "walk",
    doing: "visiting Ada",
    targetAgentId: "a1",
    lastBriefAt: 1_700_000_000_000,
  },
};

export const robotFixture: RobotState = {
  agentId: "a1",
  ownerUserId: "u1",
  ownerName: "Ante",
  repoId: "r1",
  seatId: "seat-1",
  provider: "claude-code",
  model: "claude-sonnet-4-5",
  effort: "high",
  permissionMode: "auto",
  status: "working",
  action: "editing",
  taskTitle: "Fix #8",
  taskSummary: "Implement protocol package",
  issueNumber: 8,
  prNumber: 0,
  worktreeBranch: "protocol/8-wire-types",
  handRaised: false,
  statusReason: "",
  bubbleEmits: { toolCalls: 12, fileEdits: 4, testRuns: 2, toolFailures: 1 },
  lastActivityAt: 1_700_000_003_000,
};

export const floorFixture: FloorState = {
  floorId: "f1",
  name: "Regulus Office",
  slug: "regulus-office",
  paletteId: "oak-sky",
  layoutTemplateId: "office-l2-small",
  repos: [
    {
      repoId: "r1",
      owner: "regulus-advanced-systems",
      name: "regulus-office",
      defaultBranch: "master",
      isPrimary: true,
    },
  ],
  robots: { a1: robotFixture },
  desks: {
    "seat-1": { seatId: "seat-1", agentId: "a1" },
    "seat-2": { seatId: "seat-2", agentId: "" },
  },
  decor: {
    d1: {
      id: "d1",
      kind: "picture",
      wallId: "north",
      x: 2,
      y: 1.5,
      w: 1,
      h: 0.75,
      imageUrl: "/uploads/d1.png",
      placedBy: "u1",
    },
  },
  queue: [
    {
      id: "q1",
      position: 0,
      kind: "issue",
      refNumber: 9,
      repoId: "r1",
      title: "#9 Wire the queue",
      prompt: "Implement issue #9",
      provider: "codex",
      model: "gpt-5-codex",
      effort: "",
      permissionMode: "on-request",
      autoWorktree: true,
      state: "queued",
      agentId: "",
      prNumber: 0,
      reason: "",
      createdBy: "u1",
      ownerName: "Ante",
      createdAt: 1_700_000_004_000,
      startedAt: 0,
      finishedAt: 0,
    },
  ],
  issues: {
    "r1#8": {
      repoId: "r1",
      number: 8,
      title: "protocol: enums, room state shapes",
      state: "open",
      labels: ["area:protocol", "type:task"],
      assignees: [],
      author: "azivkovi",
      url: "https://github.com/regulus-advanced-systems/regulus-office/issues/8",
      updatedAt: 1_700_000_005_000,
    },
  },
  pulls: {
    "r1#71": {
      repoId: "r1",
      number: 71,
      title: "Make baseline quality gates green",
      state: "closed",
      labels: [],
      assignees: ["azivkovi"],
      author: "azivkovi",
      url: "https://github.com/regulus-advanced-systems/regulus-office/pull/71",
      updatedAt: 1_700_000_006_000,
      draft: false,
      merged: true,
      headBranch: "ci/71-gates",
      checksState: "success",
      reviewState: "approved",
    },
  },
  services: {
    svc1: {
      id: "svc1",
      agentId: "a1",
      port: 5173,
      url: "/p/f1/a/a1/port/5173/",
      title: "Vite dev server",
      pid: 42,
      address: "0.0.0.0",
      localOnly: false,
      shared: false,
      firstSeenAt: 1_700_000_007_000,
      lastSeenAt: 1_700_000_008_000,
    },
  },
  whiteboardVersion: 3,
  carriedCards: {
    s1: {
      sessionId: "s1",
      userId: "u1",
      cardKind: "issue",
      repoId: "r1",
      number: 8,
      pickedAt: 1_700_000_009_000,
    },
  },
  queueSettings: { maxRunning: 2, maxPerOwner: 1 },
};
