/**
 * Room settings (SPEC §9.1 "Room interiors", D8, D21; #182): a project
 * room's desk count and decor style. The interior itself is generated by
 * `generateRoom` in @regulus/floor-layout from the room's size, door side and
 * these two settings.
 *
 * - Room managers (floor `manage`; office owners and admins have it on every
 *   room) change them; everyone with room access may read them.
 * - The desk count is bounded by what the room's size fits, and shrinking is
 *   refused while a robot sits at a desk that would go away.
 * - A decor style changes props, materials and lighting, never function:
 *   seats, desks, boards, the door and the spawn point stay where they are.
 */
import { z } from "zod";
import { DOOR_SIDES } from "./compound.ts";
import type { FloorAccess } from "./enums.ts";

/** Lair decor styles a room can pick (SPEC §12). The first is the default. */
export const DECOR_STYLES = ["ops_room", "lab", "workshop", "war_room"] as const;
export type DecorStyle = (typeof DECOR_STYLES)[number];

export const DEFAULT_DECOR_STYLE: DecorStyle = "ops_room";

/** A new room starts vanilla: one desk of four seats (D8). */
export const DEFAULT_DESK_COUNT = 1;

/** Seats around one desk; seat ids are `d<desk>s<seat>`. */
export const SEATS_PER_DESK = 4;

/** Upper bound on any room's desk count (the 12×12 room's grid); the size usually caps lower. */
export const MAX_DESK_COUNT = 16;

export function isDecorStyle(value: unknown): value is DecorStyle {
  return typeof value === "string" && (DECOR_STYLES as readonly string[]).includes(value);
}

/** `GET|PUT /api/floors/:floorId/room-settings`. */
export function roomSettingsPath(floorId: string): string {
  return `/api/floors/${encodeURIComponent(floorId)}/room-settings`;
}

/** Body of `PUT /api/floors/:floorId/room-settings`; omitted fields keep their value. */
export const UpdateRoomSettingsRequest = z
  .object({
    deskCount: z.number().int().min(1).max(MAX_DESK_COUNT).optional(),
    decorStyle: z.enum(DECOR_STYLES).optional(),
  })
  .refine((b) => b.deskCount !== undefined || b.decorStyle !== undefined, {
    message: "nothing to change",
  });
export type UpdateRoomSettingsRequest = z.infer<typeof UpdateRoomSettingsRequest>;

/** What a room's interior is generated from besides its settings: size in tiles and door side. */
export const RoomShape = z.object({
  /** Tiles along x and z (1 tile = 2 m). */
  width: z.number().int().positive(),
  depth: z.number().int().positive(),
  doorSide: z.enum(DOOR_SIDES),
});
export type RoomShape = z.infer<typeof RoomShape>;

/** What the settings panel shows. */
export const RoomSettingsInfo = z.object({
  floorId: z.string(),
  deskCount: z.number().int().min(1),
  decorStyle: z.enum(DECOR_STYLES),
  /** The room's size, or null when the office does not know it yet. */
  size: RoomShape.nullable(),
  /** Most desks the room's size fits (the current count when the size is unknown). */
  maxDeskCount: z.number().int().min(1),
  /** Desk numbers (1-based) with a robot at one of their seats; these cannot be removed. */
  occupiedDesks: z.array(z.number().int().positive()),
  /**
   * False while the room is still drawn from a pre-compound floor template:
   * its decor style may change, its desk count only once it is generated.
   */
  generated: z.boolean(),
  /** The caller may change the settings (room manager). */
  canManage: z.boolean(),
});
export type RoomSettingsInfo = z.infer<typeof RoomSettingsInfo>;

/** Room managers change room settings (no zod, so the web bundle can use it alone). */
export function mayManageRoomSettings(access: FloorAccess | null | undefined): boolean {
  return access === "manage";
}

/** Smallest desk count that keeps every occupied desk (1-based desk numbers). */
export function minDeskCountFor(occupiedDesks: readonly number[]): number {
  return Math.max(1, ...occupiedDesks);
}
