/**
 * Typed layer over `JsonRpcConnection`, using the bindings generated by
 * `codex app-server generate-ts` (see generated/README.md). Only the methods
 * this adapter calls are mapped; params come straight from the generated
 * `ClientRequest` union so a protocol change shows up as a type error on
 * regeneration.
 */

import type { PipedProcess } from "../types.ts";
import type {
  ClientRequest,
  InitializeResponse,
  ServerNotification,
  ServerRequest,
} from "./generated/index.ts";
import type {
  CancelLoginAccountResponse,
  GetAccountRateLimitsResponse,
  GetAccountResponse,
  LoginAccountResponse,
  ThreadResumeResponse,
  ThreadStartResponse,
  TurnInterruptResponse,
  TurnStartResponse,
  TurnSteerResponse,
} from "./generated/v2/index.ts";
import {
  type IncomingRequest,
  JsonRpcConnection,
  type ProcessExit,
  type RpcErrorBody,
  type RpcId,
} from "./jsonrpc.ts";

/** Result types of the client→server methods the adapter uses. */
export interface CodexResponses {
  initialize: InitializeResponse;
  "thread/start": ThreadStartResponse;
  "thread/resume": ThreadResumeResponse;
  "turn/start": TurnStartResponse;
  "turn/steer": TurnSteerResponse;
  "turn/interrupt": TurnInterruptResponse;
  "account/read": GetAccountResponse;
  "account/login/start": LoginAccountResponse;
  "account/login/cancel": CancelLoginAccountResponse;
  "account/rateLimits/read": GetAccountRateLimitsResponse;
}
export type CodexMethod = keyof CodexResponses;
export type CodexParams<M extends CodexMethod> = Extract<ClientRequest, { method: M }>["params"];

export type CodexNotification = ServerNotification;
export type CodexServerRequest = ServerRequest;

export interface CodexClientHandlers {
  onNotification?: (notification: CodexNotification) => void;
  onServerRequest?: (request: CodexServerRequest) => void;
  onExit?: (exit: ProcessExit) => void;
  requestTimeoutMs?: number;
}

/** `clientInfo` sent on `initialize`; identifies the office in Codex logs. */
export const CLIENT_INFO = {
  name: "regulus_office",
  title: "Regulus Office",
  version: "0.0.0",
} as const;

export class CodexRpcClient {
  readonly connection: JsonRpcConnection;

  constructor(proc: PipedProcess, handlers: CodexClientHandlers = {}) {
    this.connection = new JsonRpcConnection(proc, {
      requestTimeoutMs: handlers.requestTimeoutMs,
      // The generated unions are the documented contract; the server is the
      // only producer, so method/params are trusted to match them.
      onNotification: (method, params) =>
        handlers.onNotification?.({ method, params } as CodexNotification),
      onRequest: (req: IncomingRequest) =>
        handlers.onServerRequest?.({
          method: req.method,
          id: req.id,
          params: req.params,
        } as CodexServerRequest),
      onExit: handlers.onExit,
    });
  }

  request<M extends CodexMethod>(
    method: M,
    params: CodexParams<M>,
    timeoutMs?: number,
  ): Promise<CodexResponses[M]> {
    return this.connection.request(method, params, timeoutMs) as Promise<CodexResponses[M]>;
  }

  /** `initialize` + `initialized`, required once per connection before anything else. */
  async initialize(): Promise<InitializeResponse> {
    const result = await this.request("initialize", {
      clientInfo: { ...CLIENT_INFO },
      capabilities: null,
    });
    await this.connection.notify("initialized");
    return result;
  }

  respond(id: RpcId, result: unknown): Promise<void> {
    return this.connection.respond(id, result);
  }

  respondError(id: RpcId, error: RpcErrorBody): Promise<void> {
    return this.connection.respondError(id, error);
  }

  close(): Promise<ProcessExit> {
    return this.connection.close();
  }

  get exited(): Promise<ProcessExit> {
    return this.connection.exited;
  }
}
